# Generated by Django 4.2.9 on 2026-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_hospital_doctor_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department_category',
            field=models.CharField(blank=True, help_text='Department category for analytics', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='performance_rating',
            field=models.IntegerField(blank=True, help_text='Performance rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary', max_digits=10, null=True),
        ),
    ]
