# Generated by Django 4.2.9 on 2026-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patientprofile_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(help_text='Dosage details (e.g. 1 tablet, 5ml)', max_length=100),
        ),
    ]
